# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install --use-mirrors pyfasta bx-python nose numpy
  - python setup.py install
script: python setup.py test
